---
# Clone Suma repo
- name: clone suma
  git: repo=https://github.com/suma-project/Suma dest=/vagrant/suma accept_hostkey=yes
  tags: suma

- name: populate mysql db
  mysql_db: name=suma state=import target=/vagrant/suma/service/config/schema_w_sample.sql

- name: restart mysql (mariadb)
  service: name=mariadb state=restarted

# Suma symlinks
- name: create sumaserver symlink
  file: src=/vagrant/suma/service/web/ dest=/var/www/html/sumaserver state=link

- name: create suma web directory
  file: path=/var/www/html/suma/ state=directory

- name: create suma client symlink
  file: src=/vagrant/suma/web/ dest=/var/www/html/suma/client state=link

- name: create suma analysis symlink
  file: src=/vagrant/suma/analysis/ dest=/var/www/html/suma/analysis state=link

# Suma logs
- name: create suma log directory
  file: path=/vagrant/suma/sumalogs/ state=directory

- name: create suma log file
  file: path=/vagrant/suma/sumalogs/sumaserver.log state=touch mode="u=rw,g=rw,o=rw"

# Index.html
- name: copy index.html
  copy: src=/vagrant/configs/index.html dest=/var/www/html

# Suma configs
- name: link service config
  copy: src=/vagrant/configs/service/config/config.yaml dest=/vagrant/suma/service/config/config.yaml

- name: link service/web config
  copy: src=/vagrant/configs/service/web/config/config.yaml dest=/vagrant/suma/service/web/config/config.yaml

- name: link analysis config
  copy: src=/vagrant/configs/analysis/config/config.yaml dest=/vagrant/suma/analysis/config/config.yaml

- name: link client config
  copy: src=/vagrant/configs/web/config/spaceassessConfig.js dest=/vagrant/suma/web/config/spaceassessConfig.js
