# Suma configs
- name: link service config
  copy: src=/vagrant/configs/service/config/config.yaml dest=/vagrant/suma/service/config/config.yaml

- name: link service/web config
  copy: src=/vagrant/configs/service/web/config/config.yaml dest=/vagrant/suma/service/web/config/config.yaml

- name: link analysis config
  copy: src=/vagrant/configs/analysis/config/config.yaml dest=/vagrant/suma/analysis/config/config.yaml

- name: link client config
  copy: src=/vagrant/configs/web/config/spaceassessConfig.js dest=/vagrant/suma/web/config/spaceassessConfig.js`