---
# Install development dependencies
- name: install node
  apt: name=nodejs

- name: symlink node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: install npm
  apt: name=npm

- name: install grunt-cli
  command: npm install -g grunt-cli

- name: install bower
  command: npm install -g bower

- name: update global npm packages
  command: npm update -g

# Prepare development environment
- name: install suma npm packages
  command: npm install --no-bin-links
  args:
    chdir: /vagrant/suma/analysis/
  tags: npm-install

- name: install compass
  command: bundle install
  args:
    chdir: /vagrant/suma/analysis

- name: prepare development environment
  become: yes
  become_method: sudo
  become_user: vagrant
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/rvm/gems/{{ ruby_version }}/bin"
  command: grunt prepareDevEnv
  args:
    chdir: /vagrant/suma/analysis/
