project_name: suma
bundler_ruby: 2.5.1

rvm1_rubies:
  - ruby-2.5.1
rvm1_user: "vagrant"

# MySQL configs (geerlinguy.mysql)
mysql_root_password: 'mysqlrootpassword'
mysql_bind_address: '0.0.0.0'
mysql_enabled_on_startup: yes

mysql_databases:
  - name: suma
    encoding: utf8
mysql_users:
  - name: suma
    host: 'localhost'
    password: 12345
    priv: 'suma.*:ALL'

# Apache configs (geerlingguy.apache)
apache_vhosts_filename: "{{ project_name }}.conf"
apache_allow_override: "All"
apache_options: "+Indexes +FollowSymLinks +Includes"
apache_vhosts:
  - servername: "localhost"
    documentroot: "/var/www/html"
    extra_parameters: |
      <Directory "/var/www/html/sumaserver/">
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} -s [OR]
          RewriteCond %{REQUEST_FILENAME} -l [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^.*$ - [NC,L]
          RewriteRule ^.*$ index.php [NC,L]
        </Directory>

# apache_global_vhost_settings: |
  # Options Indexes FollowSymLinks Includes
  # DirectoryIndex index.php index.html
  # AddType application/x-httpd-php .php
  # AddType text/html .html
  # AddType text/html .htm
  # AddOutputFilter INCLUDES .shtml .html .php
# apache_vhosts:
#   - servername: "localhost"
#     extra_parameters: |
#       <Directory "/var/www/html/sumaserver/">
#         RewriteEngine On
#         RewriteCond %{REQUEST_FILENAME} -s [OR]
#         RewriteCond %{REQUEST_FILENAME} -l [OR]
#         RewriteCond %{REQUEST_FILENAME} -d
#         RewriteRule ^.*$ - [NC,L]
#         RewriteRule ^.*$ index.php [NC,L]
#       </Directory>
#
#       # Suma aliases for development assets
#       Alias /suma/analysis/src/styles "/var/www/html/suma/analysis/.tmp/styles/"
#       Alias /suma/analysis/src/fonts "/var/www/html/suma/analysis/.tmp/fonts/"
#   - servername: "local.dev"
#     extra_parameters: |
#       <Directory "/var/www/html">
#           AllowOverride All
#           Options +Indexes +FollowSymLinks +Includes
#           Require all granted
#       </Directory>

# PHP configs (geerlinguy.php)
php_enablerepo: remi
php_version: "7.1"
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_date_timezone: "America/New_York"
php_enable_apc: false
php_opcache_enable: "0"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-pdo
  - php-mbstring
  - php-mcrypt
  - php-mysql
  - php-xml
  - php-curl
