# Copy this file to a new file `config.yaml`

# Display errors
showErrors: false

# Change baseUrl to the URL for your Suma Query Server. If you
# used a directory other than `sumaserver` in the "Suma Software Installation"
# section in `INSTALL.md`, that should be reflected in this URL.
serverIO:
    baseUrl: http://localhost/sumaserver/query

# Change analysisBaseUrl to the URL for your analysis tools
analysisBaseUrl: http://localhost:19679/suma/analysis/reports/
# Configuration for nightly report
# Default Timezone. See: http://php.net/manual/en/timezones.php
# Date display format. See: http://php.net/manual/en/function.date.php
# Recipient e-mail addresses separated by commas
# Error recipient e-mail addresses separated by comma
nightly:
    timezone: America/New_York
    displayFormat: m-d-Y
    recipients: nobody@example.com
    errorRecipients: nobody@example.com
    emailFrom: "Suma Reports Test <nobody@example.com>"
    emailSubj: "Suma Nightly Report Test:"
