# Install development dependencies
- name: install xdebug
  apt: pkg=php5-xdebug

- name: add xdebug path
  ini_file: dest=/etc/php5/apache2/php.ini section=xdebug option=zend_extension value="/usr/lib/php5/20121212+lfs/xdebug.so"
  tags: set_xdebug_path

- name: enable xdebug profiler
  ini_file: dest=/etc/php5/apache2/php.ini section=xdebug option=xdebug.profiler_enable value=1
  tags: enable_xdebug_profiler

- name: set xdebug output directory
  ini_file: dest=/etc/php5/apache2/php.ini section=xdebug option=xdebug.profiler_output_dir value="/tmp"
  tags: set_xdebug_directory

- name: restart apache
  service: name=apache2 state=restarted
  tags: apacherestart

- name: cron job for xdebug logs
  cron: name="remove cachegrind files" minute="15" job="cd /tmp && rm cachegrind.*"

- name: install webgrind
  git: repo=https://github.com/jokkedk/webgrind.git dest=/var/www/html/webgrind accept_hostkey=yes

- name: install Ruby
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby2.0
    - ruby2.0-dev

- name: create symlink for Ruby
  file: src=/usr/bin/ruby2.0 dest=/usr/local/bin/ruby state=link

- name: create symlink for Ruby gems
  file: src=/usr/bin/gem2.0 dest=/usr/local/bin/gem state=link

- name: install bundler
  command: gem install bundler

- name: install phpunit
  apt: name=phpunit

- name: install node
  apt: name=nodejs

- name: symlink node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: install npm
  apt: name=npm

- name: install grunt-cli
  command: npm install -g grunt-cli

- name: install bower
  command: npm install -g bower

# Prepare development environment
- name: install suma npm packages
  command: npm install
  args:
    chdir: /vagrant/suma/analysis/
  tags: npm-install

- name: install compass
  command: bundle install
  args:
    chdir: /vagrant/suma/analysis

- name: prepare development environment
  command: grunt prepareDevEnv
  args:
    chdir: /vagrant/suma/analysis/
