---
- hosts: suma-vagrant
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - vars/main.yml
  pre_tasks:
    - yum:
        pkg: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - mysql-devel
        - vim
  roles:
    - role: basic-setup
    - role: dev-open-firewall
      ports:
        - 80
        - 3000
    - role: geerlingguy.mysql
    - role: geerlingguy.apache
    - role: geerlingguy.repo-remi
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: suma-ansible
